server:
  port: 9100
  servlet:
    context-path: /pvs-api

message:
  exception: "exception error"
  success: "success!"
  fail: "fail!"
  invalid:
    url: "Invalid URL ..."

webClient:
  baseUrl:
    sonar: "https://sonarcloud.io/api"
    github: "https://api.github.com/graphql"
    test: ""

spring:
  profiles:
    active: test
  datasource:
    url: ${DB_URL}
    username: ${PVS_DB_USER}
    password: ${PVS_DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Taipei

